### ISSUE TITLE
Gtk theme not doing anything

### ISSUE THREAD

**Issue by Batres3** [InioX/matugen-themes#25]
I have made the templates, and checked that the files exist, and are placed in the correct directories, but when I launch any gtk app, it has the default theme.

Am I missing anything? Do I have to set any other config anywhere else?

I am on Arch and Wayland

**Comment by sabi-31** [comment]
I am having the same issue.

**Comment by gs-101** [comment]
Did you create the correct file, viz. `$XDG_CONFIG_HOME/gtk.css`?

I had the same issue, and was able to get GTK 4 theming working by using the correct file name.

Not sure if GTK 3 applications are working.

Additionally, I got an updated version of the GTK theme from #19.

Here is my setup:

1. Configure Matugen (`$XDG_CONFIG_HOME/matugen/config.toml`):

```toml
[templates.gtk3]
input_path = 'templates/gtk.css'
output_path = '~/.config/gtk-3.0/matugen.css' # Can be any name.

[templates.gtk4]
input_path = 'templates/gtk.css'
output_path = '~/.config/gtk-4.0/matugen.css' # Can be any name.
```

2. Add the template:

<details>

```css
/*
* GTK Colors
* Generated with Matugen
* Thanks CocoJamb0O <https://github.com/CocoJamb0O>
* See: <https://github.com/InioX/matugen-themes/issues/19>
*/

@define-color accent_color @accent_bg_color;
@define-color accent_bg_color {{colors.primary_fixed_dim.default.hex}};
@define-color accent_fg_color {{colors.on_primary_fixed.default.hex}};
@define-color card_bg_color {{colors.surface.default.hex}};
@define-color card_fg_color @window_fg_color;
@define-color card_shade_color {{colors.shadow.default.hex}};
@define-color destructive_color @error_color;
@define-color destructive_bg_color @error_bg_color;
@define-color destructive_fg_color @error_fg_color;
@define-color error_color {{colors.error.default.hex}};
@define-color error_bg_color {{colors.error_container.default.hex}};
@define-color error_fg_color {{colors.on_error_container.default.hex}};
@define-color headerbar_bg_color @window_bg_color;
@define-color headerbar_fg_color @window_fg_color;
@define-color headerbar_backdrop_color @window_bg_color;
@define-color headerbar_border_color @window_bg_color;
@define-color headerbar_shade_color {{colors.shadow.default.hex}};
@define-color popover_bg_color @window_bg_color;
@define-color popover_fg_color @window_fg_color;
@define-color secondary_sidebar_bg_color @window_bg_color;
@define-color secondary_sidebar_fg_color @window_fg_color;
@define-color secondary_sidebar_backdrop_color @window_bg_color;
@define-color secondary_sidebar_boder_color @window_bg_color;
@define-color secondary_sidebar_shade_color {{colors.shadow.default.hex}};
@define-color sidebar_bg_color @window_bg_color;
@define-color sidebar_fg_color @window_fg_color;
@define-color sidebar_backdrop_color @window_bg_color;
@define-color sidebar_shade_color {{colors.shadow.default.hex}};
@define-color success_color {{colors.secondary.default.hex}};
@define-color success_bg_color {{colors.secondary_container.default.hex}};
@define-color success_fg_color {{colors.on_secondary_container.default.hex}};
@define-color view_bg_color {{colors.surface.default.hex}};
@define-color view_fg_color @window_fg_color;
@define-color warning_color {{colors.tertiary.default.hex}};
@define-color warning_bg_color {{colors.tertiary_container.default.hex}};
@define-color warning_fg_color {{colors.on_tertiary_container.default.hex}};
@define-color window_bg_color {{colors.surface_dim.default.hex}};
@define-color window_fg_color {{colors.on_surface.default.hex}};

/*
* GTK 4 Colors
* Generated with Matugen
* Thanks CocoJamb0O <https://github.com/CocoJamb0O>
* See: <https://github.com/InioX/matugen-themes/issues/19>
*/

:root {
    /* Default colors, because Material Design works with surfaces, not colors. */
    --accent-blue: #3584e4;
    --accent-teal: #2190a4;
    --accent-green: #3a944a;
    --accent-yellow: #c88800;
    --accent-orange: #ed5b00;
    --accent-red: #e62d42;
    --accent-pink: #d56199;
    --accent-purple: #9141ac;
    --accent-slate: #6f8396;

    --accent-bg-color: @accent_bg_color;
    --accent-fg-color: @accent_fg_color;
    --destructive-bg-color: @destructive_bg_color;
    --destructive-fg-color: @destructive_fg_color;
    --success-bg-color: @success_bg_color;
    --success-fg-color: @success_fg_color;
    --warning-bg-color: @warning_bg_color;
    --warning-fg-color: @warning_fg_color;
    --error-bg-color: @error_bg_color;
    --error-fg-color: @error_fg_color;
    --window-bg-color: @window_bg_color;
    --window-fg-color: @window_fg_color;
    --view-bg-color: @view_bg_color;
    --view-fg-color: @view_fg_color;
    --headerbar-bg-color: @headerbar_bg_color;
    --headerbar-fg-color: @headerbar_fg_color;
    --headerbar-border-color: @headerbar_border_color;
    --headerbar-backdrop-color: @headerbar_backdrop_color;
    --headerbar-shade-color: @headerbar_shade_color;
    --headerbar-darker-shade-color: @headerbar_darker_shade_color;
    --sidebar-bg-color: @sidebar_bg_color;
    --sidebar-fg-color: @sidebar_fg_color;
    --sidebar-backdrop-color: @sidebar_backdrop_color;
    --sidebar-border-color: @sidebar_border_color;
    --sidebar-shade-color: @sidebar_shade_color;
    --secondary-sidebar-bg-color: @secondary_sidebar_bg_color;
    --secondary-sidebar-fg-color: @secondary_sidebar_fg_color;
    --secondary-sidebar-backdrop-color: @secondary_sidebar_backdrop_color;
    --secondary-sidebar-border-color: @secondary_sidebar_border_color;
    --secondary-sidebar-shade-color: @secondary_sidebar_shade_color;
    --card-bg-color: @card_bg_color;
    --card-fg-color: @card_fg_color;
    --card-shade-color: @card_shade_color;
    --dialog-bg-color: @dialog_bg_color;
    --dialog-fg-color: @dialog_fg_color;
    --popover-bg-color: @popover_bg_color;
    --popover-fg-color: @popover_fg_color;
    --popover-shade-color: @popover_shade_color;
    --thumbnail-bg-color: @thumbnail_bg_color;
    --thumbnail-fg-color: @thumbnail_fg_color;
    --shade-color: @shade_color;
    --scrollbar-outline-color: @scrollbar_outline_color;
}
```
</details>

3. Import the color definitions:

`$XDG_CONFIG_HOME/gtk-3.0/gtk.css` (It's **gtk.css**, not any other name!)

```css
@import 'matugen.css';
```

For GTK 4, replace the `gtk-3.0` in the path with `gtk-4.0`.

I use Guix, so I tested by running `guix shell gnome-calculator -- gnome-calculator`:

![Image](https://github.com/user-attachments/assets/168ea77f-da4a-48e8-a636-54013ee01f4a)
